"""Two ready-to-copy example contracts bundled with the CLI's `example`
command. The full scenario library (Phase 16) lives in the repo's top-level
examples/ directory instead, since those are meant to be read and validated
by tests rather than regenerated by the installed package.
"""

from __future__ import annotations

from pathlib import Path

from groundspec.contract.factory import new_contract
from groundspec.contract.serialization import dump_document


def _section(contract: dict[str, object], key: str) -> dict[str, object]:
    value = contract[key]
    assert isinstance(value, dict)
    return value


def _linkedin_post_example() -> dict[str, object]:
    contract = new_contract(
        task_id="write-launch-post",
        raw_user_brief="write a linkedin post announcing our launch",
        normalized_problem_statement="No announcement content exists yet for the product launch.",
        goal="Produce one LinkedIn post announcing the launch, ready to publish.",
        target_users=["prospective customers following the company page"],
        expected_deliverables=[{"name": "post_draft", "description": "Final LinkedIn post text"}],
        risk_overlays=["informational", "external_communication"],
        risk_level="low",
    )
    routing = _section(contract, "routing")
    routing["domain_packs"] = [{"pack_id": "content", "version": "0.1.0"}]
    _section(contract, "scope")["constraints"] = [
        "Under 200 words",
        "No emoji unless the brand voice guide allows it",
    ]
    _section(contract, "acceptance")["criteria"] = [
        {
            "id": "under-word-limit",
            "description": "Post is at or under 200 words",
            "priority": "must",
            "verification_method": "automated_test",
            "evidence_required": "word count reported alongside the draft",
        },
        {
            "id": "no-fabricated-claims",
            "description": "No invented statistics or testimonials appear in the post",
            "priority": "must",
            "verification_method": "manual_inspection",
            "evidence_required": "reviewer confirms every claim traces to a verified fact",
        },
    ]
    _section(routing, "authorization")["requires_confirmation_for"] = ["publishing the post"]
    return contract


def _mvp_scope_example() -> dict[str, object]:
    contract = new_contract(
        task_id="scope-delivery-app-mvp",
        raw_user_brief="I want a food delivery app",
        normalized_problem_statement=(
            "No MVP scope, target user, or acceptance criteria exist yet for the requested app."
        ),
        goal="Produce a walking-skeleton MVP scope: one user, one city, one order flow, working end to end.",
        target_users=["a pilot cohort of customers in one city"],
        expected_deliverables=[
            {"name": "mvp_repo", "description": "A running MVP repository implementing the order flow"}
        ],
        risk_overlays=["informational", "filesystem_mutation"],
        risk_level="medium",
    )
    _section(contract, "routing")["domain_packs"] = [{"pack_id": "software", "version": "0.1.0"}]
    _section(contract, "scope")["non_goals"] = [
        "Multi-city support",
        "Payment processing beyond a mocked/sandbox flow",
        "Driver-side app (out of scope for this MVP)",
    ]
    _section(contract, "acceptance")["criteria"] = [
        {
            "id": "order-flow-works",
            "description": "A user can browse one restaurant's menu and place one order end to end",
            "priority": "must",
            "verification_method": "reproducible_command",
            "evidence_required": "an automated test exercising the order flow, and its output",
        }
    ]
    return contract


def write_bundled_examples(out_dir: Path) -> list[Path]:
    written = []
    for contract in (_linkedin_post_example(), _mvp_scope_example()):
        path = out_dir / f"{contract['task_id']}.toml"
        dump_document(contract, path)
        written.append(path)
    return written
