"""Renders a Task Contract as a single vendor-neutral prompt for any LLM
tool that has no native Skill/instruction-file mechanism.

This is the weakest adapter by design and says so up front: a plain prompt
has no progressive disclosure, no platform-enforced invocation, and nothing
stopping the model from ignoring it partway through a long conversation.
"""

from __future__ import annotations

from groundspec.adapters.common import render_body
from groundspec.rules.evaluator import AppliedRule

HEADER = (
    "# Vendor-neutral task prompt (generated by groundspec)\n\n"
    "**Limitations of prompt-only enforcement:** paste everything below into any chat-based AI "
    "tool as a system or first-turn message. There is no runtime enforcing it -- the model can "
    "drift from it over a long conversation, and nothing here can verify its own output. Re-paste "
    "this prompt if the conversation runs long, and run `groundspec audit` / `groundspec evaluate` "
    "yourself afterward against the same contract file to check the result independently.\n\n"
    "---\n\n"
)


def render_generic_prompt(
    contract: dict[str, object],
    applied_rules: list[AppliedRule],
) -> str:
    return HEADER + render_body(contract, applied_rules)
